"use client"
import { Montserrat } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { VideoPlayer } from './components/getUrlYoutube/VideoHomePage'

const inter = Montserrat({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
// const Router = useRouter()
export default function RootLayout({ children }) {
  return (
    <html lang="fr" className='w-full h-full'>      
      <body className={`${inter.className} w-screen`}>
        <VideoPlayer className="-z-10 w-screen h-full" videoId='QdBZY2fkU-0'/>
        <header className='z-10 w-screen bg-black mx-0.5 my-0.5 fixed'>

        </header>
        
          {children}
      </body>
    </html>
  )
}
